## ndarray

In [3]:
import numpy as np

##1d array
arr1=np.array([1,2,3,4,5])
print(type(arr1))


##2d array
arr2=np.array([[1,2,3,4],
               [5,6,7,8]])


##3d array
arr3=np.array([
    [[1,2,3,4],
     [5,6,7,8]],

    [[1,2,3,4],
     [5,6,7,8]]
])


<class 'numpy.ndarray'>


## array attributes

In [ ]:
## dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

## shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

## data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

## size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(5,)
(2, 4)
(2, 2, 4)
int64
int64
int64
5
8
16


## ndarray data type

In [ ]:
arr=np.array([1,2,3])
print(arr.dtype)

arr=np.array([1.4,2.4,3.4])
print(arr.dtype)

## upcasting
arr=np.array([1,2,3.4])
print(arr.dtype)

## selecting a data type for an array
arr=np.array([1,2,3])
arr=arr.astype(np.int16)
print(arr.dtype)


int64
float64
float64
int16


## ndarray creation from existing data

In [ ]:
## list
lst=[10,20,30,40,50]
arr=np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)
print("\n")
mixed_lst=[10,True,'hello',10.4]
arr=np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


['10' 'True' 'hello' '10.4']
<class 'numpy.ndarray'>
<U32


In [22]:
# tuple
tpl=(10,20,30)
arr=np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[10 20 30]
<class 'numpy.ndarray'>
int64
1
(3,)


In [25]:
## set
st={1,2,3}
arr=np.array(st)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

{1, 2, 3}
<class 'numpy.ndarray'>
object
0
()


In [29]:
# dictionary
dc={'a':10, 'b':20, 'c':30}
keys=dc.keys()
values=dc.values()
items=dc.items()
## keys
arr=np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

## values
arr=np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

## items
arr=np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
1
(3,)
[10 20 30]
<class 'numpy.ndarray'>
int64
1
(3,)
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
2
(3, 2)


## array creation with random values

In [11]:
#np.random.rand(shape)
import numpy as np
arr=np.random.rand(2,3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

##random integer(start,end,shape)
import numpy as np
arr=np.random.randint(1,20,(2,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

##random float(start,end,shape)
import numpy as np
arr=np.random.uniform(1,20,(3,5))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[[0.88274622 0.7379374  0.61455271]
 [0.63697035 0.46097691 0.94986352]]
<class 'numpy.ndarray'>
float64
2
(2, 3)
[[ 7  8 17]
 [10 17 16]]
<class 'numpy.ndarray'>
int32
2
(2, 3)
[[ 7.15671997  6.6706924  14.99259571 15.61253882 10.17383566]
 [ 1.96902849 16.05934056  1.53506001 10.40443772  9.65966116]
 [ 4.09766068  9.32874495  4.93514932  7.22948675  4.9160038 ]]
<class 'numpy.ndarray'>
float64
2
(3, 5)


## array creation with range

In [19]:
## array arrange(start,end,step)
arr=np.arange(1,20,5).reshape(2,2)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[[ 1  6]
 [11 16]]
<class 'numpy.ndarray'>
int64
2
(2, 2)


In [ ]:
## np.linspace(start,end(included),point)

arr=np.linspace(1,10,10)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
float64
1
(10,)


In [22]:
## np.logspace(start,end(included),point)

arr=np.logspace(0,4,5)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
<class 'numpy.ndarray'>
float64
1
(5,)


## ndarray Manipulation

In [ ]:
import numpy as np
arr=np.random.randint(1,100,size=(10,5))
arr.shape


(10, 5)

In [17]:
arr

array([[15, 54, 23, 15, 64],
       [43, 50, 89, 79, 20],
       [ 5, 88, 74, 77, 61],
       [70, 64, 19,  1,  6],
       [29, 81, 25, 93, 91],
       [73, 69,  9, 95, 68],
       [95, 91, 88, 57, 86],
       [17, 77, 69, 93, 67],
       [53, 12, 40, 33, 84],
       [17, 99, 82, 50, 51]], dtype=int32)

In [15]:
b=arr.reshape(5,10)
b.shape


(5, 10)

In [16]:
b

array([[15, 54, 23, 15, 64, 43, 50, 89, 79, 20],
       [ 5, 88, 74, 77, 61, 70, 64, 19,  1,  6],
       [29, 81, 25, 93, 91, 73, 69,  9, 95, 68],
       [95, 91, 88, 57, 86, 17, 77, 69, 93, 67],
       [53, 12, 40, 33, 84, 17, 99, 82, 50, 51]], dtype=int32)

In [26]:
## row wise flattening
row_flat=np.ravel(b,order='C')
print(row_flat)

[15 54 23 15 64 43 50 89 79 20  5 88 74 77 61 70 64 19  1  6 29 81 25 93
 91 73 69  9 95 68 95 91 88 57 86 17 77 69 93 67 53 12 40 33 84 17 99 82
 50 51]


In [27]:
## column wise flattening
column_flat=np.ravel(b,order='F')
print(column_flat)

[15  5 29 95 53 54 88 81 91 12 23 74 25 88 40 15 77 93 57 33 64 61 91 86
 84 43 70 73 17 17 50 64 69 77 99 89 19  9 69 82 79  1 95 93 50 20  6 68
 67 51]


In [29]:
## concatenate array
a=np.random.randint(1,20,size=(2,3))
b=np.random.randint(30,50,size=(2,3))


In [31]:
## row wise
con_row=np.concatenate((a,b),axis=0)
print(con_row)

## column wise
con_col=np.concatenate((a,b),axis=1)
print(con_col)

[[15  3 16]
 [12 15 17]
 [36 37 39]
 [36 43 37]]
[[15  3 16 36 37 39]
 [12 15 17 36 43 37]]


In [34]:
## transpose
mat=np.array([[10,20,30],
              [40,50,60]
              ])
transpose=mat.T
print(transpose)

[[10 40]
 [20 50]
 [30 60]]


In [37]:
## array split
a=np.random.randint(1,20,size=(20,))
splited_array=np.array_split(a,4)
print(splited_array)

[array([17,  4,  4,  1, 12], dtype=int32), array([10, 12,  9,  4,  8], dtype=int32), array([ 3,  1, 16, 11, 15], dtype=int32), array([ 5,  9, 18, 10, 12], dtype=int32)]


## nd array searching

In [50]:
x=np.array([10,30,40,50,12,14])
index=np.where(x==40)
print(index)
index=np.where(x>14)
print(index)

## max value
maxi_value=np.argmax(x)
print(maxi_value)
## min value
min_value=np.argmin(x)
print(min_value)

(array([2]),)
(array([1, 2, 3]),)
3
0


## Counting

In [51]:
a=np.random.randint(1,100,size=(100,))
print(a)

[75 75 68 95 15 79  4 54 22 62 93 12  6 68 40 29 69 11 97  4 21 76 88 60
 11 88 52 42 53 65 78 30 83 14 87 38 71 67 32 87 68 14 15 88 77 68 64 10
 58  7 97 62  2 40 21 74 57 99 67 96 86 55 14 29  8  2 49 90 63 51 64 49
 79 87  9 58 50 89 81 92 60 18 65 92 15 19 95 77 73 90 20 39 42 84  7 88
 39 61 84 85]


In [54]:
value_greater_60=np.count_nonzero(a>40)
print(value_greater_60)

unique_value=np.unique(a)
print(unique_value)
unique_values=np.unique(a,return_counts=True)
print(unique_values)

66
[ 2  4  6  7  8  9 10 11 12 14 15 18 19 20 21 22 29 30 32 38 39 40 42 49
 50 51 52 53 54 55 57 58 60 61 62 63 64 65 67 68 69 71 73 74 75 76 77 78
 79 81 83 84 85 86 87 88 89 90 92 93 95 96 97 99]
(array([ 2,  4,  6,  7,  8,  9, 10, 11, 12, 14, 15, 18, 19, 20, 21, 22, 29,
       30, 32, 38, 39, 40, 42, 49, 50, 51, 52, 53, 54, 55, 57, 58, 60, 61,
       62, 63, 64, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 78, 79, 81, 83,
       84, 85, 86, 87, 88, 89, 90, 92, 93, 95, 96, 97, 99], dtype=int32), array([2, 2, 1, 2, 1, 1, 1, 2, 1, 3, 3, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 4, 1, 1, 1, 1,
       2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 3, 4, 1, 2, 2, 1, 2, 1, 2, 1]))
