## ndarray

In [ ]:
import numpy as np

##1d array
arr1=np.array([1,2,3,4,5])
print(type(arr1))


##2d array
arr2=np.array([[1,2,3,4],
               [5,6,7,8]])


##3d array
arr3=np.array([
    [[1,2,3,4],
     [5,6,7,8]],

    [[1,2,3,4],
     [5,6,7,8]]
])


<class 'numpy.ndarray'>
1
2
3


## array attributes

In [ ]:
## dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

## shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

## data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

## size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(5,)
(2, 4)
(2, 2, 4)
int64
int64
int64
5
8
16


## ndarray data type

In [ ]:
arr=np.array([1,2,3])
print(arr.dtype)

arr=np.array([1.4,2.4,3.4])
print(arr.dtype)

## upcasting
arr=np.array([1,2,3.4])
print(arr.dtype)

## selecting a data type for an array
arr=np.array([1,2,3])
arr=arr.astype(np.int16)
print(arr.dtype)


int64
float64
float64
int16


## ndarray creation from existing data

In [ ]:
## list
lst=[10,20,30,40,50]
arr=np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)
print("\n")
mixed_lst=[10,True,'hello',10.4]
arr=np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


['10' 'True' 'hello' '10.4']
<class 'numpy.ndarray'>
<U32


In [22]:
# tuple
tpl=(10,20,30)
arr=np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[10 20 30]
<class 'numpy.ndarray'>
int64
1
(3,)


In [25]:
## set
st={1,2,3}
arr=np.array(st)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

{1, 2, 3}
<class 'numpy.ndarray'>
object
0
()


In [29]:
# dictionary
dc={'a':10, 'b':20, 'c':30}
keys=dc.keys()
values=dc.values()
items=dc.items()
## keys
arr=np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

## values
arr=np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

## items
arr=np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
1
(3,)
[10 20 30]
<class 'numpy.ndarray'>
int64
1
(3,)
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
2
(3, 2)
